Added search input text font option
react-navigation/search-layout pull request #21
Opened 2020-11-17 12:43 UTC by summerkiflain

I am using custom font in my whole app, so I added support for custom fontFamily in this PR.
- For now I am using patch-package to monkey patch the latest version, this PR will help me remove that dependency.

2020-12-17 12:28 UTC, summerkiflain commented
Hi @eriveltonelias, please review, I have added another commit, all checks are passing now, and please please publish on npm after merging this.

2020-12-19 20:22 UTC, eriveltonelias requested changes
thanks for your PR! I just left a few comments.

2020-12-19 20:22 UTC, eriveltonelias commented on src/SearchLayout.js
> +            textFontFamily={this.props.searchInputTextFontFamily}
could you add this new prop to the types definition file too?

2020-12-19 20:22 UTC, eriveltonelias commented on src/SearchBar.ios.js
> +                this.props.textFontFamily ? { fontFamily: this.props.textFontFamily } : null
let's do this way:
```js
color: this.props.tintColor || '#007AFF',
...(this.props.textFontFamily &&  { fontFamily: this.props.textFontFamily })

```

2020-12-21 09:59 UTC, summerkiflain commented on src/SearchLayout.js
> +            textFontFamily={this.props.searchInputTextFontFamily}
done!

2020-12-21 09:59 UTC, summerkiflain commented on src/SearchBar.ios.js
> +                this.props.textFontFamily ? { fontFamily: this.props.textFontFamily } : null
Thanks for the tip.

2020-12-21 10:01 UTC, summerkiflain commented
@eriveltonelias PR updated, thanks for the feedback.

2021-01-04 13:22 UTC, eriveltonelias approved these changes
thanks!

2021-01-04 13:23 UTC, merged

2021-01-05 05:17 UTC, summerkiflain commented
@eriveltonelias any chance you can publish this on npm?